apiVersion: v1
kind: Service
metadata:
  name: php-blog-service
  labels:
    app: php-blog
spec:
  selector:
    app: php-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # Change to LoadBalancer if using a cloud provider
